affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cuda:0
grid: 5
grid_eps: 0.02
grid_range:
- -1
- 1
k: 4
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 1
symbolic.funs_name.0:
- - 1/x^2
  - 1/x^2
  - 1/x^2
  - '0'
  - 1/x^2
  - tan
  - tan
  - 1/x^3
  - exp
  - '0'
  - '0'
  - 1/x^3
  - x^2
  - x^2
  - '0'
  - abs
  - x
  - 1/x^3
  - 1/x^2
  - '0'
  - 1/x^3
  - 1/x^3
  - '0'
  - '0'
  - 1/x^3
  - 1/x^2
  - 1/x^2
  - 1/x^3
  - '0'
  - 1/x^3
  - exp
  - '0'
  - '0'
  - exp
  - x
  - '0'
  - 1/x^3
  - 1/x^2
  - exp
  - 1/x^4
  - '0'
  - x
  - exp
  - x^2
  - exp
  - 1/x^2
  - x
  - '0'
  - '0'
  - '0'
  - x
  - 1/x^3
  - 1/x^2
  - '0'
  - exp
  - '0'
  - '0'
  - '0'
  - 1/x^3
  - 1/x
  - x^2
  - '0'
  - 1/x^2
  - '0'
  - exp
  - x^2
  - 1/x^3
  - 1/x
  - x^2
  - '0'
  - '0'
  - '0'
  - x^2
  - '0'
  - '0'
  - 1/x^3
  - '0'
  - exp
  - 1/x^3
  - exp
  - '0'
  - '0'
  - x^2
  - 1/x^3
  - exp
  - x
  - 1/x^3
  - x^2
  - 1/x^3
  - 1/x^4
  - 1/x^2
  - x^2
  - '0'
  - exp
  - 1/x^4
  - 1/x^2
  - exp
  - x
  - 1/x^2
  - x^2
  - '0'
  - '0'
  - 1/x^3
  - '0'
  - 1/x^3
  - x
  - x
  - '0'
  - x^2
  - '0'
  - 1/x
  - x
  - abs
  - '0'
  - '0'
  - 1/x^2
  - x
  - '0'
  - '0'
  - 1/x^3
  - x^2
  - '0'
  - 1/x^2
  - x^2
  - x^2
  - '0'
  - exp
  - '0'
  - x
  - '0'
  - 1/x^2
  - x
  - cos
  - 1/x^3
  - exp
  - x
  - '0'
  - x
  - 1/x^3
  - 1/x^2
  - x^2
- - x
  - exp
  - 1/x^2
  - 1/x^3
  - 1/x^2
  - sin
  - tan
  - 1/x^4
  - 1/x^2
  - 1/x^4
  - '0'
  - 1/x^3
  - cos
  - tan
  - '0'
  - x^2
  - x
  - 1/x^3
  - x^2
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - 1/x^3
  - 1/x^2
  - 1/x^2
  - '0'
  - '0'
  - 1/x^3
  - x^2
  - 1/x^3
  - 1/x^3
  - exp
  - x
  - 1/x^4
  - '0'
  - 1/x^2
  - exp
  - 1/x^4
  - '0'
  - x
  - x^2
  - tan
  - exp
  - exp
  - x
  - '0'
  - 1/x^3
  - '0'
  - x
  - 1/x^3
  - 1/x^2
  - '0'
  - exp
  - '0'
  - 1/x^3
  - '0'
  - '0'
  - 1/x^2
  - x^2
  - '0'
  - exp
  - '0'
  - x^5
  - x^2
  - '0'
  - abs
  - x^2
  - 1/x^3
  - '0'
  - '0'
  - tan
  - '0'
  - 1/x^3
  - 1/x^3
  - 1/x^3
  - x
  - 1/x^3
  - 1/x^2
  - '0'
  - '0'
  - tan
  - '0'
  - exp
  - x
  - '0'
  - exp
  - '0'
  - '0'
  - exp
  - 1/x^2
  - 1/x^3
  - x^2
  - '0'
  - 1/x^2
  - exp
  - x
  - 1/x
  - x^2
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - x
  - '0'
  - x^2
  - 1/x^4
  - exp
  - x
  - abs
  - 1/x^3
  - '0'
  - exp
  - x
  - '0'
  - '0'
  - '0'
  - x
  - 1/x^3
  - 1/x^2
  - x
  - x^2
  - '0'
  - 1/x
  - 1/x^3
  - x
  - 1/x^3
  - x
  - x
  - abs
  - 1/x^3
  - exp
  - x
  - 1/x^3
  - x
  - '0'
  - 1/x^2
  - 1/x^2
symbolic.funs_name.1:
- - sin
  - x
symbolic_enabled: true
width:
- - 141
  - 0
- - 2
  - 0
- - 1
  - 0
