affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cuda:0
grid: 5
grid_eps: 0.02
grid_range:
- -1
- 1
k: 4
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 1
symbolic.funs_name.0:
- - '0'
  - x
  - exp
  - '0'
  - 1/x^2
  - '0'
  - '0'
  - 1/x^3
  - 1/x^2
  - '0'
  - '0'
  - '0'
  - '0'
  - x^0.5
  - '0'
  - sin
  - exp
  - '0'
  - '0'
  - '0'
  - '0'
  - 1/x^3
  - 1/x^3
  - '0'
  - '0'
  - '0'
  - 1/x
  - 1/x^3
  - '0'
  - '0'
  - exp
  - '0'
  - '0'
  - exp
  - x
  - '0'
  - 1/x^3
  - exp
  - 1/x^2
  - 1/x^3
  - '0'
  - x
  - x^2
  - tan
  - exp
  - exp
  - x
  - '0'
  - 1/x^3
  - 1/x^2
  - x
  - '0'
  - 1/x^2
  - '0'
  - exp
  - '0'
  - '0'
  - '0'
  - '0'
  - 1/x^2
  - exp
  - 1/x^3
  - 1/x
  - 1/x^3
  - tan
  - x
  - '0'
  - exp
  - x^2
  - 1/x^3
  - '0'
  - '0'
  - x^2
  - '0'
  - '0'
  - 1/x^3
  - '0'
  - '0'
  - '0'
  - 1/x^2
  - 1/x^3
  - '0'
  - tan
  - '0'
  - exp
  - x
  - '0'
  - x^2
  - '0'
  - 1/x^3
  - exp
  - '0'
  - '0'
  - exp
  - '0'
  - 1/x^2
  - exp
  - x
  - exp
  - x^2
  - '0'
  - '0'
  - '0'
  - 1/x^3
  - 1/x^3
  - x
  - x
  - '0'
  - x^2
  - '0'
  - exp
  - x
  - '0'
  - 1/x^3
  - '0'
  - x
  - x
  - 1/x^3
  - '0'
  - 1/x^3
  - exp
  - 1/x^3
  - exp
  - x
  - exp
  - 1/x^3
  - 1/x^2
  - '0'
  - x
  - '0'
  - exp
  - x
  - '0'
  - '0'
  - x^2
  - x
  - 1/x^3
  - x
  - 1/x^3
  - '0'
  - 1/x^2
- - cos
  - x
  - 1/x
  - '0'
  - exp
  - '0'
  - 1/x^2
  - '0'
  - exp
  - 1/x^3
  - '0'
  - '0'
  - cos
  - x^2
  - 1/x^3
  - '0'
  - x
  - 1/x^3
  - tan
  - 1/x^3
  - '0'
  - '0'
  - '0'
  - 1/x^3
  - 1/x^3
  - '0'
  - 1/x^2
  - 1/x^3
  - '0'
  - '0'
  - exp
  - '0'
  - 1/x^3
  - exp
  - x
  - '0'
  - '0'
  - 1/x^2
  - exp
  - '0'
  - '0'
  - exp
  - x^2
  - tan
  - exp
  - 1/x^2
  - x
  - '0'
  - 1/x^3
  - '0'
  - x
  - '0'
  - 1/x^2
  - '0'
  - exp
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - x^2
  - '0'
  - 1/x^2
  - '0'
  - cos
  - x
  - '0'
  - 1/x^2
  - x^2
  - 1/x^3
  - '0'
  - 1/x^3
  - x^2
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - 1/x^3
  - '0'
  - cos
  - 1/x^3
  - exp
  - x
  - 1/x^3
  - x^2
  - '0'
  - '0'
  - exp
  - '0'
  - '0'
  - 1/x^2
  - '0'
  - 1/x^2
  - exp
  - x
  - exp
  - x^2
  - 1/x^3
  - 1/x^3
  - 1/x^3
  - '0'
  - '0'
  - x
  - x
  - 1/x^3
  - x
  - '0'
  - x
  - x
  - x^0.5
  - 1/x^3
  - 1/x^3
  - x
  - x
  - '0'
  - '0'
  - '0'
  - x
  - 1/x^3
  - x
  - exp
  - x^2
  - 1/x^3
  - exp
  - '0'
  - x
  - 1/x^3
  - x
  - x
  - '0'
  - '0'
  - x
  - x
  - '0'
  - x
  - '0'
  - '0'
  - x
symbolic.funs_name.1:
- - 1/x^2
  - exp
symbolic_enabled: true
width:
- - 141
  - 0
- - 2
  - 0
- - 1
  - 0
